#ifndef LEXER_H
#define LEXER_H

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>

#define FIRST_RESERVED 256

typedef enum {
    // Single character tokens
    TOKEN_SEMICOLON = ';',
    TOKEN_COMMA = ',',
    TOKEN_DOT = '.',
    TOKEN_LPAREN = '(',
    TOKEN_RPAREN = ')',
    TOKEN_LBRACE = '{',
    TOKEN_RBRACE = '}',
    TOKEN_LBRACKET = '[',
    TOKEN_RBRACKET = ']',
    TOKEN_PLUS = '+',
    TOKEN_MINUS = '-',
    TOKEN_STAR = '*',
    TOKEN_SLASH = '/',
    TOKEN_PERCENT = '%',
    TOKEN_CARET = '^',
    TOKEN_EQUAL = '=',
    TOKEN_LESS = '<',
    TOKEN_GREATER = '>',
    TOKEN_EXCLAMATION = '!',
    TOKEN_COLON = ':',
    TOKEN_QUESTION = '?',
    TOKEN_AMPERSAND = '&',
    TOKEN_PIPE = '|',
    TOKEN_TILDE = '~',
    
    // Keywords (start at FIRST_RESERVED)
    TOKEN_IF = FIRST_RESERVED,
    TOKEN_ELSE,
    TOKEN_FOR,
    TOKEN_WHILE,
    TOKEN_DO,
    TOKEN_BREAK,
    TOKEN_CONTINUE,
    TOKEN_RETURN,
    TOKEN_PROC,
    TOKEN_STRUCT,
    TOKEN_ENUM,
    TOKEN_UNION,
    TOKEN_USING,
    TOKEN_IMPORT,
    TOKEN_PACKAGE,
    TOKEN_DEFER,
    TOKEN_CAST,
    TOKEN_TRANSMUTE,
    TOKEN_DISTINCT,
    TOKEN_OPAQUE,
    TOKEN_DYNAMIC,
    TOKEN_IN,
    TOKEN_NOT_IN,
    TOKEN_TRUE,
    TOKEN_FALSE,
    TOKEN_NIL,
    TOKEN_AUTO_CAST,
    TOKEN_CONTEXT,
    TOKEN_FOREIGN,
    TOKEN_EXPORT,
    TOKEN_INLINE,
    TOKEN_NO_INLINE,
    TOKEN_ODIN,
    TOKEN_INTRINSICS,
    TOKEN_TYPEID,
    TOKEN_OFFSETOF,
    TOKEN_TYPEOF,
    TOKEN_SWIZZLE,
    TOKEN_SIZE_OF,
    TOKEN_ALIGN_OF,
    TOKEN_TYPE_OF,
    TOKEN_TYPEID_OF,
    TOKEN_WHERE,
    TOKEN_WHEN,
    TOKEN_FALLTHROUGH,
    TOKEN_CASE,
    TOKEN_SWITCH,
    TOKEN_VARIANT,
    TOKEN_MATRIX,
    TOKEN_QUATERNION,
    TOKEN_COMPLEX,
    TOKEN_ATOMIC,
    TOKEN_VOLATILE,
    TOKEN_CONST,
    TOKEN_READONLY,
    TOKEN_WRITEONLY,
    TOKEN_RAWPTR,
    TOKEN_CSTRING,
    TOKEN_RUNE,
    TOKEN_UNTYPED,
    TOKEN_TYPELESS,
    TOKEN_MULTIPOINTER,
    TOKEN_SOAPOINTER,
    TOKEN_PROCEDURAL,
    TOKEN_TEMPLATE,
    TOKEN_GENERIC,
    TOKEN_POLYMORPH,
    TOKEN_COMPILE_TIME,
    TOKEN_RUNTIME,
    TOKEN_LINKAGE,
    TOKEN_STATIC,
    TOKEN_THREAD_LOCAL,
    TOKEN_GLOBAL,
    TOKEN_PRIVATE,
    TOKEN_INTERNAL,
    TOKEN_PUBLIC,
    TOKEN_PROTECTED,
    TOKEN_EXPORT_TAG,
    TOKEN_IMPORT_TAG,
    TOKEN_LINK_TAG,
    TOKEN_DEPRECATED,
    TOKEN_WARNING,
    TOKEN_DISABLED,
    TOKEN_REQUIRE,
    TOKEN_OPTIONAL,
    TOKEN_PACKED,
    TOKEN_ALIGNED,
    TOKEN_UNALIGNED,
    TOKEN_SIMD,
    TOKEN_VECTORCALL,
    TOKEN_FASTCALL,
    TOKEN_CDECL,
    TOKEN_STDCALL,
    TOKEN_THISCALL,
    TOKEN_CONVENTION,
    TOKEN_CALLING_CONVENTION,
    TOKEN_CALLING_CONVENTION_ODIN,
    TOKEN_CALLING_CONVENTION_CONTEXTLESS,
    TOKEN_CALLING_CONVENTION_STDCALL,
    TOKEN_CALLING_CONVENTION_FASTCALL,
    TOKEN_CALLING_CONVENTION_NONE,
    TOKEN_CALLING_CONVENTION_WIN64,
    TOKEN_CALLING_CONVENTION_SYSV,
    TOKEN_CALLING_CONVENTION_VECTORCALL,
    TOKEN_CALLING_CONVENTION_THISCALL,
    TOKEN_CALLING_CONVENTION_CDECL,
    TOKEN_CALLING_CONVENTION_NAKED,
    TOKEN_CALLING_CONVENTION_INLINE,
    TOKEN_CALLING_CONVENTION_NOINLINE,
    TOKEN_CALLING_CONVENTION_FORCE_INLINE,
    TOKEN_CALLING_CONVENTION_COLD,
    TOKEN_CALLING_CONVENTION_HOT,
    TOKEN_CALLING_CONVENTION_OPTIMIZE,
    TOKEN_CALLING_CONVENTION_NO_OPTIMIZE,
    TOKEN_CALLING_CONVENTION_LINK_ONCE,
    TOKEN_CALLING_CONVENTION_LINK_ONCE_ODR,
    TOKEN_CALLING_CONVENTION_WEAK,
    TOKEN_CALLING_CONVENTION_WEAK_ODR,
    TOKEN_CALLING_CONVENTION_APPENDING,
    TOKEN_CALLING_CONVENTION_INTERNAL,
    TOKEN_CALLING_CONVENTION_AVAILABLE_EXTERNALLY,
    TOKEN_CALLING_CONVENTION_LINK_ONCE_ODR_AUTO_HIDE,
    TOKEN_CALLING_CONVENTION_PRIVATE,
    TOKEN_CALLING_CONVENTION_DLL_IMPORT,
    TOKEN_CALLING_CONVENTION_DLL_EXPORT,
    TOKEN_CALLING_CONVENTION_EXTERNAL_WEAK,
    TOKEN_CALLING_CONVENTION_GHOST,
    TOKEN_CALLING_CONVENTION_COMMON,
    TOKEN_CALLING_CONVENTION_LINKER_PRIVATE,
    TOKEN_CALLING_CONVENTION_LINKER_PRIVATE_WEAK,
    TOKEN_CALLING_CONVENTION_LINKER_PRIVATE_WEAK_DEF_AUTO,
    TOKEN_CALLING_CONVENTION_PREEMPTION_SAFE,
    TOKEN_CALLING_CONVENTION_PROTECTED,
    TOKEN_CALLING_CONVENTION_EXTERNALLY_VISIBLE,
    TOKEN_CALLING_CONVENTION_HIDDEN,
    TOKEN_CALLING_CONVENTION_INTERNAL_HIDDEN,
    TOKEN_CALLING_CONVENTION_PROTECTED_HIDDEN,
    TOKEN_CALLING_CONVENTION_ANONYMOUS,
    TOKEN_CALLING_CONVENTION_SECTION,
    TOKEN_CALLING_CONVENTION_COMDAT,
    TOKEN_CALLING_CONVENTION_THREAD_LOCAL,
    TOKEN_CALLING_CONVENTION_UNNAMED_ADDR,
    TOKEN_CALLING_CONVENTION_LOCAL_UNNAMED_ADDR,
    TOKEN_CALLING_CONVENTION_EXTERNALLY_INITIALIZED,
    TOKEN_CALLING_CONVENTION_DLLIMPORT,
    TOKEN_CALLING_CONVENTION_DLLEXPORT,
    TOKEN_CALLING_CONVENTION_THREAD_LOCAL_INIT,
    TOKEN_CALLING_CONVENTION_THREAD_LOCAL_NONE,
    TOKEN_CALLING_CONVENTION_THREAD_LOCAL_LOCALDYNAMIC,
    TOKEN_CALLING_CONVENTION_THREAD_LOCAL_INITIALEXEC,
    TOKEN_CALLING_CONVENTION_THREAD_LOCAL_LOCALEXEC,
    TOKEN_CALLING_CONVENTION_THREAD_LOCAL_GENERALEXEC,
    TOKEN_CALLING_CONVENTION_THREAD_LOCAL_GENERALDYNAMIC,
    TOKEN_CALLING_CONVENTION_THREAD_LOCAL_INITIALEXEC_TLS_MODEL,
    TOKEN_CALLING_CONVENTION_THREAD_LOCAL_LOCALEXEC_TLS_MODEL,
    TOKEN_CALLING_CONVENTION_THREAD_LOCAL_LOCALDYNAMIC_TLS_MODEL,
    TOKEN_CALLING_CONVENTION_THREAD_LOCAL_GENERALDYNAMIC_TLS_MODEL,
    TOKEN_CALLING_CONVENTION_THREAD_LOCAL_GLOBALEXEC_TLS_MODEL,
    TOKEN_CALLING_CONVENTION_THREAD_LOCAL_EXEC_TLS_MODEL,
    TOKEN_CALLING_CONVENTION_THREAD_LOCAL_DYNAMIC_TLS_MODEL,
    TOKEN_CALLING_CONVENTION_THREAD_LOCAL_STATIC_TLS_MODEL,
    TOKEN_CALLING_CONVENTION_THREAD_LOCAL_EMULATED_TLS_MODEL,
    TOKEN_CALLING_CONVENTION_THREAD_LOCAL_DESCRIPTOR_TLS_MODEL,
    TOKEN_CALLING_CONVENTION_THREAD_LOCAL_NONE_TLS_MODEL,
    TOKEN_CALLING_CONVENTION_THREAD_LOCAL_UNKNOWN_TLS_MODEL,
    TOKEN_CALLING_CONVENTION_THREAD_LOCAL_INVALID_TLS_MODEL,
    TOKEN_CALLING_CONVENTION_THREAD_LOCAL_UNINITIALIZED_TLS_MODEL,
    TOKEN_CALLING_CONVENTION_THREAD_LOCAL_DESTROYED_TLS_MODEL,
    TOKEN_CALLING_CONVENTION_THREAD_LOCAL_CONSTRUCTED_TLS_MODEL,
    TOKEN_CALLING_CONVENTION_THREAD_LOCAL_CONSTINIT_TLS_MODEL,
    TOKEN_CALLING_CONVENTION_THREAD_LOCAL_CONSTDESTROY_TLS_MODEL,
    TOKEN_CALLING_CONVENTION_THREAD_LOCAL_CONSTCONSTRUCTOR_TLS_MODEL,
    TOKEN_CALLING_CONVENTION_THREAD_LOCAL_CONSTDESTRUCTOR_TLS_MODEL,
    TOKEN_CALLING_CONVENTION_THREAD_LOCAL_CONSTEXPR_TLS_MODEL,
    TOKEN_CALLING_CONVENTION_THREAD_LOCAL_CONSTEVAL_TLS_MODEL,
    TOKEN_CALLING_CONVENTION_THREAD_LOCAL_CONSTINIT_TLS_MODEL_ODIN,
    TOKEN_CALLING_CONVENTION_THREAD_LOCAL_CONSTDESTROY_TLS_MODEL_ODIN,
    TOKEN_CALLING_CONVENTION_THREAD_LOCAL_CONSTCONSTRUCTOR_TLS_MODEL_ODIN,
    TOKEN_CALLING_CONVENTION_THREAD_LOCAL_CONSTDESTRUCTOR_TLS_MODEL_ODIN,
    TOKEN_CALLING_CONVENTION_THREAD_LOCAL_CONSTEXPR_TLS_MODEL_ODIN,
    TOKEN_CALLING_CONVENTION_THREAD_LOCAL_CONSTEVAL_TLS_MODEL_ODIN,
    TOKEN_CALLING_CONVENTION_THREAD_LOCAL_CONSTINIT_TLS_MODEL_JAI,
    TOKEN_CALLING_CONVENTION_THREAD_LOCAL_CONSTDESTROY_TLS_MODEL_JAI,
    TOKEN_CALLING_CONVENTION_THREAD_LOCAL_CONSTCONSTRUCTOR_TLS_MODEL_JAI,
    TOKEN_CALLING_CONVENTION_THREAD_LOCAL_CONSTDESTRUCTOR_TLS_MODEL_JAI,
    TOKEN_CALLING_CONVENTION_THREAD_LOCAL_CONSTEXPR_TLS_MODEL_JAI,
    TOKEN_CALLING_CONVENTION_THREAD_LOCAL_CONSTEVAL_TLS_MODEL_JAI,
    TOKEN_CALLING_CONVENTION_THREAD_LOCAL_CONSTINIT_TLS_MODEL_LUA,
    TOKEN_CALLING_CONVENTION_THREAD_LOCAL_CONSTDESTROY_TLS_MODEL_LUA,
    TOKEN_CALLING_CONVENTION_THREAD_LOCAL_CONSTCONSTRUCTOR_TLS_MODEL_LUA,
    TOKEN_CALLING_CONVENTION_THREAD_LOCAL_CONSTDESTRUCTOR_TLS_MODEL_LUA,
    TOKEN_CALLING_CONVENTION_THREAD_LOCAL_CONSTEXPR_TLS_MODEL_LUA,
    TOKEN_CALLING_CONVENTION_THREAD_LOCAL_CONSTEVAL_TLS_MODEL_LUA,
    TOKEN_CALLING_CONVENTION_THREAD_LOCAL_CONSTINIT_TLS_MODEL_KAT,
    TOKEN_CALLING_CONVENTION_THREAD_LOCAL_CONSTDESTROY_TLS_MODEL_KAT,
    TOKEN_CALLING_CONVENTION_THREAD_LOCAL_CONSTCONSTRUCTOR_TLS_MODEL_KAT,
    TOKEN_CALLING_CONVENTION_THREAD_LOCAL_CONSTDESTRUCTOR_TLS_MODEL_KAT,
    TOKEN_CALLING_CONVENTION_THREAD_LOCAL_CONSTEXPR_TLS_MODEL_KAT,
    TOKEN_CALLING_CONVENTION_THREAD_LOCAL_CONSTEVAL_TLS_MODEL_KAT,
    
    // Multi-character operators
    TOKEN_DOUBLE_EQUAL,     // ==
    TOKEN_NOT_EQUAL,        // !=
    TOKEN_LESS_EQUAL,       // <=
    TOKEN_GREATER_EQUAL,    // >=
    TOKEN_LOGICAL_AND,      // &&
    TOKEN_LOGICAL_OR,       // ||
    TOKEN_DOUBLE_COLON,     // ::
    TOKEN_ARROW,            // ->
    TOKEN_DOUBLE_DOT,       // ..
    TOKEN_TRIPLE_DOT,       // ...
    TOKEN_SHIFT_LEFT,       // <<
    TOKEN_SHIFT_RIGHT,      // >>
    TOKEN_PLUS_EQUAL,       // +=
    TOKEN_MINUS_EQUAL,      // -=
    TOKEN_STAR_EQUAL,       // *=
    TOKEN_SLASH_EQUAL,      // /=
    TOKEN_PERCENT_EQUAL,    // %=
    TOKEN_CARET_EQUAL,      // ^=
    TOKEN_AMPERSAND_EQUAL,  // &=
    TOKEN_PIPE_EQUAL,       // |=
    TOKEN_TILDE_EQUAL,      // ~=
    TOKEN_SHIFT_LEFT_EQUAL, // <<=
    TOKEN_SHIFT_RIGHT_EQUAL,// >>=
    TOKEN_PLUS_PLUS,        // ++
    TOKEN_MINUS_MINUS,      // --
    TOKEN_QUESTION_QUESTION,// ??
    TOKEN_EXCLAMATION_EQUAL,// !=
    TOKEN_EXCLAMATION_EXCLAMATION, // !!
    TOKEN_QUESTION_COLON,   // ?:
    TOKEN_AMPERSAND_AMPERSAND, // &&
    TOKEN_PIPE_PIPE,        // ||
    TOKEN_CARET_CARET,      // ^^
    TOKEN_TILDE_TILDE,      // ~~
    TOKEN_DOUBLE_LESS,      // <<
    TOKEN_DOUBLE_GREATER,   // >>  // >>>
    TOKEN_DOUBLE_STAR,      // **
    TOKEN_DOUBLE_SLASH,     // //
    TOKEN_DOUBLE_PERCENT,   // %%
    TOKEN_DOUBLE_CARET,     // ^^
    TOKEN_DOUBLE_AMPERSAND, // &&
    TOKEN_DOUBLE_PIPE,      // ||
    TOKEN_DOUBLE_TILDE,     // ~~
    TOKEN_TRIPLE_EQUAL,     // ===
    TOKEN_TRIPLE_NOT_EQUAL, // !==
    TOKEN_TRIPLE_LESS,      // <<<
    TOKEN_TRIPLE_GREATER,   // >>>
    TOKEN_TRIPLE_LESS_EQUAL,// <<<=
    TOKEN_TRIPLE_GREATER_EQUAL,// >>>=
    TOKEN_TRIPLE_STAR,      // ***
    TOKEN_TRIPLE_SLASH,     // ///
    TOKEN_TRIPLE_PERCENT,   // %%%
    TOKEN_TRIPLE_CARET,     // ^^^
    TOKEN_TRIPLE_AMPERSAND, // &&&
    TOKEN_TRIPLE_PIPE,      // |||
    TOKEN_TRIPLE_TILDE,     // ~~~
    TOKEN_QUADRUPLE_EQUAL,  // ====
    TOKEN_QUADRUPLE_NOT_EQUAL,// !===
    TOKEN_QUADRUPLE_LESS,   // <<<<
    TOKEN_QUADRUPLE_GREATER,// >>>>
    TOKEN_QUADRUPLE_LESS_EQUAL,// <<<<=
    TOKEN_QUADRUPLE_GREATER_EQUAL,// >>>>=
    TOKEN_QUADRUPLE_STAR,   // ****
    TOKEN_QUADRUPLE_SLASH,  // ////
    TOKEN_QUADRUPLE_PERCENT,// %%%%
    TOKEN_QUADRUPLE_CARET,  // ^^^^
    TOKEN_QUADRUPLE_AMPERSAND,// &&&&
    TOKEN_QUADRUPLE_PIPE,   // ||||
    TOKEN_QUADRUPLE_TILDE,  // ~~~~
    TOKEN_QUINTUPLE_EQUAL,  // =====
    TOKEN_QUINTUPLE_NOT_EQUAL,// !=====
    TOKEN_QUINTUPLE_LESS,   // <<<<<
    TOKEN_QUINTUPLE_GREATER,// >>>>>
    TOKEN_QUINTUPLE_LESS_EQUAL,// <<<<=
    TOKEN_QUINTUPLE_GREATER_EQUAL,// >>>>=
    TOKEN_QUINTUPLE_STAR,   // *****
    TOKEN_QUINTUPLE_SLASH,  // /////
    TOKEN_QUINTUPLE_PERCENT,// %%%%%
    TOKEN_QUINTUPLE_CARET,  // ^^^^^
    TOKEN_QUINTUPLE_AMPERSAND,// &&&&&
    TOKEN_QUINTUPLE_PIPE,   // |||||
    TOKEN_QUINTUPLE_TILDE,  // ~~~~~
    TOKEN_SEXTUPLE_EQUAL,   // ======
    TOKEN_SEXTUPLE_NOT_EQUAL,// !======
    TOKEN_SEXTUPLE_LESS,    // <<<<<<
    TOKEN_SEXTUPLE_GREATER, // >>>>>>
    TOKEN_SEXTUPLE_LESS_EQUAL,// <<<<<=
    TOKEN_SEXTUPLE_GREATER_EQUAL,// >>>>>=
    TOKEN_SEXTUPLE_STAR,    // ******
    TOKEN_SEXTUPLE_SLASH,   // //////
    TOKEN_SEXTUPLE_PERCENT, // %%%%%%
    TOKEN_SEXTUPLE_CARET,   // ^^^^^^
    TOKEN_SEXTUPLE_AMPERSAND,// &&&&&&
    TOKEN_SEXTUPLE_PIPE,    // ||||||
    TOKEN_SEXTUPLE_TILDE,   // ~~~~~~
    TOKEN_SEPTUPLE_EQUAL,   // =======
    TOKEN_SEPTUPLE_NOT_EQUAL,// !=======
    TOKEN_SEPTUPLE_LESS,    // <<<<<<<
    TOKEN_SEPTUPLE_GREATER, // >>>>>>>
    TOKEN_SEPTUPLE_LESS_EQUAL,// <<<<<<=
    TOKEN_SEPTUPLE_GREATER_EQUAL,// >>>>>>>=
    TOKEN_SEPTUPLE_STAR,    // *******
    TOKEN_SEPTUPLE_SLASH,   // ///////
    TOKEN_SEPTUPLE_PERCENT, // %%%%%%%
    TOKEN_SEPTUPLE_CARET,   // ^^^^^^^
    TOKEN_SEPTUPLE_AMPERSAND,// &&&&&&&
    TOKEN_SEPTUPLE_PIPE,    // |||||||
    TOKEN_SEPTUPLE_TILDE,   // ~~~~~~~
    TOKEN_OCTUPLE_EQUAL,    // ========
    TOKEN_OCTUPLE_NOT_EQUAL,// !========
    TOKEN_OCTUPLE_LESS,     // <<<<<<<<
    TOKEN_OCTUPLE_GREATER,  // >>>>>>>>
    TOKEN_OCTUPLE_LESS_EQUAL,// <<<<<<<=
    TOKEN_OCTUPLE_GREATER_EQUAL,// >>>>>>>>
    TOKEN_OCTUPLE_STAR,     // ********
    TOKEN_OCTUPLE_SLASH,    // ////////
    TOKEN_OCTUPLE_PERCENT,  // %%%%%%%%
    TOKEN_OCTUPLE_CARET,    // ^^^^^^^^
    TOKEN_OCTUPLE_AMPERSAND,// &&&&&&&&
    TOKEN_OCTUPLE_PIPE,     // ||||||||
    TOKEN_OCTUPLE_TILDE,    // ~~~~~~~~
    TOKEN_NONUPLE_EQUAL,    // =========
    TOKEN_NONUPLE_NOT_EQUAL,// !=========
    TOKEN_NONUPLE_LESS,     // <<<<<<<<<
    TOKEN_NONUPLE_GREATER,  // >>>>>>>>>
    TOKEN_NONUPLE_LESS_EQUAL,// <<<<<<<<=
    TOKEN_NONUPLE_GREATER_EQUAL,// >>>>>>>>>>
    TOKEN_NONUPLE_STAR,     // *********
    TOKEN_NONUPLE_SLASH,    // /////////
    TOKEN_NONUPLE_PERCENT,  // %%%%%%%%%
    TOKEN_NONUPLE_CARET,    // ^^^^^^^^^
    TOKEN_NONUPLE_AMPERSAND,// &&&&&&&&&
    TOKEN_NONUPLE_PIPE,     // |||||||||
    TOKEN_NONUPLE_TILDE,    // ~~~~~~~~~
    TOKEN_DECUPLE_EQUAL,    // ==========
    TOKEN_DECUPLE_NOT_EQUAL,// !==========
    TOKEN_DECUPLE_LESS,     // <<<<<<<<<<
    TOKEN_DECUPLE_GREATER,  // >>>>>>>>>>
    TOKEN_DECUPLE_LESS_EQUAL,// <<<<<<<<<<=
    TOKEN_DECUPLE_GREATER_EQUAL,// >>>>>>>>>>>>=
    TOKEN_DECUPLE_STAR,     // **********
    TOKEN_DECUPLE_SLASH,    // //////////
    TOKEN_DECUPLE_PERCENT,  // %%%%%%%%%%
    TOKEN_DECUPLE_CARET,    // ^^^^^^^^^^
    TOKEN_DECUPLE_AMPERSAND,// &&&&&&&&&&
    TOKEN_DECUPLE_PIPE,     // ||||||||||
    TOKEN_DECUPLE_TILDE,    // ~~~~~~~~~~
    
    // Literals
    TOKEN_IDENTIFIER,
    TOKEN_STRING,
    TOKEN_NUMBER,
    TOKEN_CHARACTER,
    
    // Special
    TOKEN_NEWLINE,
    TOKEN_EOF,
    TOKEN_INVALID
} TokenType;

typedef struct {
    TokenType type;
    const char* start;
    int length;
    int line;
    int column;
} Token;

typedef struct {
    const char* start;
    const char* current;
    int line;
    int column;
    int start_column;
} Lexer;

void lexer_init(Lexer* lexer, const char* source);
Token lexer_next_token(Lexer* lexer);
const char* token_type_to_string(TokenType type);
void print_token(Token token);

#endif // LEXER_H